version: '3'

services:
  app:
    build: ./
    container_name: java-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/librarydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345




#  postgres:
#    image: 'postgres:15'
#    container_name: 'java-postgres'
#    environment:
#      - 'POSTGRES_USER=postgres'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'
#      - 'POSTGRES_DB=librarydb'
#
#  app:
#   build: ./
#   container_name: 'rest_api'
#   ports:
#     - 8080:8080

